CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS passes (
  id INTEGER PRIMARY KEY,
  user TEXT NOT NULL,
  reason TEXT NOT NULL,
  date TEXT NOT NULL,
  comment TEXT
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY,
  passId INTEGER,
  action TEXT,
  FOREIGN KEY (passId) REFERENCES passes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pass_logs (
  id INTEGER PRIMARY KEY,
  passId INTEGER NOT NULL,
  action TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  FOREIGN KEY (passId) REFERENCES passes(id) ON DELETE CASCADE
);